version: '2'
services:
    cadastroapi-app:
        image: cadastroapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cadastroapi-mysql:3306/userapijwt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRINGBOOT_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cadastroapi-mysql:
        extends:
            file: mysql.yml
            service: cadastroapi-mysql
